version: "3.8"

services:
    fastapi:
        build:
            context: ./docker/api
            dockerfile: Dockerfile
        container_name: fastapi
        environment:
            PYTHONPATH: /workspace/app
        volumes:
            - ./app:/workspace/app
            - ./scripts:/workspace/scripts
            - ./.vscode:/workspace/.vscode
            - ./.devcontainer:/workspace/.devcontainer
            - ./.env:/workspace/.env
        working_dir: /workspace
        command: bash -c "./scripts/run.sh"
        ports:
            - 8888:8000
        networks:
            - backend

networks:
    backend:
